### PR TITLE
Adding documents with Single<DocumentReference> besides Completable

### PR DESCRIPTION
**Pull request by ofalvai**
Created a new method called `addAsSingle()`, which returns `Single<DocumentReference>` instead of `Completable` when adding Documents to Collections. This is useful when we want to know the auto-generated ID of the new Document.

I'm not sure about the name of the method and the functional interface (`AddOnSubscribeSingle`). Do you have a better idea? Maybe the original `AddOnSubscribe` class can implement both `SingleOnSubscribe` and `CompletableOnSubscribe`.

### CODE REVIEW

**Comment by btrautmann** [comment]
@ofalvai thanks for the contribution! I like the idea of having `AddOnSubscribe` implement both `SingleOnSubscribe` and `CompletableOnSubscribe`. Because the implementation of this class is hidden behind `RxFirestoreDb`, I think this is OK as callers won't interact directly with it anyway. Could as also rename `addAsSingle` to something like `addAndProvideDocId` instead, since we're not adding it _as_ a `Single`, that method just happens to return a `Single`? Let me know if you disagree. Also, there are now some conflicts in this branch because of the previous PR making it in.

**Comment by btrautmann** [comment]
Let's also get this versioned at `1.2.0` as it adds new functionality.

**Comment by btrautmann** [comment]
Oh, and we should also add this to the Kotlin extension functions.

**Comment by ofalvai** [comment]
I have made the changes, let me know if anything is still missing or wrong.

**Comment by btrautmann** [comment]
Closing and re-opening in hopes circleci will do its thing.

**Review by btrautmann — APPROVED** [review]

**Pull request merged**
